# Generated by Django 4.2 on 2023-04-04 17:26

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_final', models.DateField()),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='projetos', variations={'thumb': (124, 124)}, verbose_name='Imagem')),
                ('ferramentas', models.TextField()),
                ('gerente_projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_projeto.desenvolvedores')),
            ],
        ),
    ]
