# Generated by Django 4.2 on 2023-04-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desenvolvedores',
            new_name='Funcionarios',
        ),
    ]
